[build-system]
requires = ["setuptools>=61",
	    "setuptools_scm",
	    "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "protopop"
version = '0.0.0'
description = "Tools to simulate protostellar populations"
dependencies = ['astropy',
	        'astroquery',
		'h5py',
		'initial_mass_function',
		'numpy',
		'scipy',
		'tqdm',
		'uv']

dynamic = ['optional-dependencies','authors','license','requires-python','readme']

[project.gui-scripts]
get-protopop-data = "protopop.util.get_data:retriever"

[tool.setuptools.packages]
find = {}

[project.urls]
Homepage = "https://github.com/richardson-t/protopop"
Issues = "https://github.com/richardson-t/protopop/issues"